name = "lottery-saas-bot"
main = "src/index.js"
compatibility_date = "2024-01-29"

[[d1_databases]]
binding = "DB"
database_name = "lottery-saas-db"
database_id = "a8aa70a2-d041-42a7-8c6e-44f89a79a138"
